services:
  diario-do-clima-backend-server:
    restart: always
    build: ./
    ports:
      - "127.0.0.1:8000:8000"
    env_file: .env
    command: gunicorn config.wsgi:application -w 2 -b :8000 --reload

  diario-do-clima-backend-celery-beat:
    restart: always
    build: ./
    env_file: .env
    command: celery -A config beat -l INFO

  diario-do-clima-backend-celery-worker:
    restart: always
    build: ./
    env_file: .env
    command: celery -A config worker -l INFO

  diario-do-clima-redis:
    restart: always
    image: docker.io/redis:7.2-alpine
    ports:
      - "127.0.0.1:6379:6379"
