version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
  
  web:
    restart: always
    build: ./web/
    expose:
      - "8000"
    links:
      - postgres:postgres
    volumes:
      - ./web/:/opt/app/
      - web-static:/usr/src/app/static
    command: /usr/local/bin/gunicorn config.wsgi:application -w 2 -b :8000 --reload

  nginx:
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - web-static:/www/static
    links:
      - web:web

volumes:
  web-static:
  pgdata:
