version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.9
        environment:
          DIARIO_SECRET_KEY: django-insecure-41u6jo_*yg2=1tabsc8ul3-!m!n1hywuj9$t_bv*jb2ju+s9-3
          DIARIO_DEBUG: True
          DIARIO_ALLOWED_HOSTS: localhost
          DIARIO_DB_URL: postgres://postgres@localhost/postgres?sslmode=disable
          DIARIO_PAGSEGURO_EMAIL: email@gmail.com
          DIARIO_PAGSEGURO_TOKEN: ADD0FRA720C4B6AA4058FD1F36DAG4
          DIARIO_PAGSEGURO_WS_URL: https://ws.sandbox.pagseguro.uol.com.br
          DIARIO_QUERIDO_DIARIO_API_URL: http://mock:3000
          CELERY_BROKER_URL: redis://redis:6379          
          CELERY_RESULT_BACKEND: redis://redis:6379
          EMAIL_HOST: smtp.gmail.com
          EMAIL_HOST_USER: ops@jurema.la
          EMAIL_HOST_PASSWORD: password
          EMAIL_PORT: 587

      - image: cimg/postgres:14.2
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

    steps:
      - checkout
      - run: 
          command: |            
            poetry install
      - run:
          name: Running tests
          command: |            
            poetry run python manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app