version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          command: |
            curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
            poetry install
      - run:
          name: Running tests
          command: |            
            poetry run web/manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app