services:
  diario-do-clima-backend-server:
    restart: always
    build: ./
    ports:
      - "8000:8000"
    links:
      - diario-do-clima-postgres:postgres
      - diario-do-clima-redis:redis
    volumes:
      - web-static:/opt/app/static
    env_file: .env
    command: gunicorn config.wsgi:application -w 2 -b :8000 --reload
    profiles:
      - dev
      - prod

  diario-do-clima-backend-celery-beat:
    restart: always
    build: ./
    links:
      - diario-do-clima-postgres:postgres
      - diario-do-clima-redis:redis
    env_file: .env
    command: celery -A config beat -l INFO
    profiles:
      - dev
      - prod

  diario-do-clima-backend-celery-worker:
    restart: always
    build: ./
    links:
      - diario-do-clima-postgres:postgres
      - diario-do-clima-redis:redis
    env_file: .env
    command: celery -A config worker -l INFO
    profiles:
      - dev
      - prod

  diario-do-clima-redis:
    image: redis:latest
    ports:
      - "6379:6379"
    profiles:
      - dev
      - prod

  diario-do-clima-postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file: postgres.env
    profiles:
      - dev

volumes:
  web-static:
  pgdata:
